import brandsData from "./brands.json";

// Generated by apps/web/scripts/build-brands.mjs. Maps a normalized brand name to
// its logo path + whether it reads as a clean glyph under the monochrome (white)
// treatment. Filled-emblem logos (mono=false) and brands with no logo fall back
// to an initials chip.
const BRANDS = brandsData as Record<string, { display: string; logo: string; mono: boolean }>;

function norm(s: string): string {
  return s
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export interface BrandMark {
  logo: string;
  mono: boolean;
}

/** Logo mark for a brand label, or null if we don't have one. */
export function brandMark(label: string | null | undefined): BrandMark | null {
  if (!label) return null;
  const e = BRANDS[norm(label)];
  return e ? { logo: e.logo, mono: e.mono } : null;
}
