import brandsData from "./brands.json";

// Generated by apps/web/scripts/build-brands.mjs. Maps a normalized brand name
// to its logo path; brands without a logo fall back to an initials chip.
const BRANDS = brandsData as Record<string, { display: string; logo: string }>;

function norm(s: string): string {
  return s
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

/** Logo path for a brand label, or null if we don't have one. */
export function brandLogo(label: string | null | undefined): string | null {
  if (!label) return null;
  return BRANDS[norm(label)]?.logo ?? null;
}
